const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000},hasTouch:true}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));let reads=0,fail=false;
  const times=Array.from({length:201},(_,i)=>i/100),numeric=fn=>times.map((t,i)=>i>=30&&i<60?null:fn(t,i));
  const telemetry={duration:2,maxGap:.15,streams:{carState:{times,values:{speed:numeric(t=>72+Math.sin(t*8)),clusterSpeed:numeric(()=>73),cruiseSpeed:numeric(()=>80),acceleration:numeric(t=>Math.sin(t*6)),gas:numeric(()=>10),brake:numeric(()=>0),steeringAngle:numeric(t=>Math.sin(t*4)*8),steeringRate:numeric(t=>Math.cos(t*4)*32),driverTorque:numeric(()=>.2),epsTorque:numeric(()=>.1),rpm:numeric(()=>1500),steeringPressed:times.map((t,i)=>i===11),gasPressed:times.map(()=>true),brakePressed:times.map(()=>false),regenBraking:times.map(()=>false),standstill:times.map(()=>false),parkingBrake:times.map(()=>false),brakeHoldActive:times.map(()=>false)}},carControl:{times,values:{latActive:times.map(()=>true),longActive:times.map(()=>true),targetAcceleration:numeric(()=>.2),targetAngle:numeric(()=>2),commandTorque:numeric(()=>.1)}},carOutput:{times,values:{outputTorque:numeric(()=>.1)}}}};
  Object.assign(telemetry.streams.carControl.values,{enabled:times.map(()=>true),plannedAcceleration:numeric(()=>.3),jerk:numeric(()=>.4),accelRequested:times.map(()=>false),decelRequested:times.map(()=>true),long_off:times.map(()=>false),long_pid:times.map(()=>true),long_stopping:times.map(()=>false),long_starting:times.map(()=>false),commandCurvature:numeric(()=>.00123)});
  Object.assign(telemetry.streams.carOutput.values,{outputGas:numeric(()=>25),outputBrake:numeric(()=>40),outputAcceleration:numeric(()=>-.5)});
  telemetry.streams.controlsState={times,values:{desiredAngle:numeric(()=>3),actualCurvature:numeric(()=>.0012),desiredCurvature:numeric(()=>.0013),actualLateralAccel:numeric(()=>.8),desiredLateralAccel:numeric(()=>1.2)}};
  telemetry.streams.carControl.values.targetAngle=times.map(()=>null); // Older controller angle fallback.
  const data={route:'Telemetry test',key:'telemetry-v1',duration:2,logStart:0,logEnd:2,warnings:[],video:{start:0,duration:2},frames:Array.from({length:41},(_,i)=>({t:i/20,id:i,valid:true,lanes:[],edges:[],lp:[],es:[],leads:[],liveTracksValid:false}))};
  await page.route('https://rv.test/**',route=>{
   const p=new URL(route.request().url()).pathname;
   if(p==='/api/logs')return route.fulfill({json:{logs:[]}});
   if(p.endsWith('/telemetry')){reads++;return route.fulfill(fail?{status:404,json:{error:'차량 정보가 없습니다. 재생성해 주세요.'}}:{json:telemetry})}
   if(p.endsWith('/data'))return route.fulfill({json:data});
   if(p.endsWith('/video'))return route.fulfill({body:fs.readFileSync((process.env.RV_TEST_VIDEO||'/tmp/roadviewer-test.mp4')),contentType:'video/mp4'});
   const name=p.startsWith('/view/')?'index.html':p.replace('/assets/','');
   return route.fulfill({body:fs.readFileSync('roadviewer/app/web/'+name),contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':name.endsWith('.png')?'image/png':'image/svg+xml'});
  });
  await page.goto('https://rv.test/view/one/');await page.waitForFunction(()=>!document.getElementById('play').disabled);assert.equal(reads,0,'road tab should not load telemetry');
  await page.locator('#telemetryTab').click();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));assert.equal(reads,1);assert(await page.locator('#roadView').isHidden());assert(await page.locator('#video').isVisible());
  assert.equal(await page.locator('.telemetry-chart').count(),6);
  await page.evaluate(()=>setTime(.11));assert((await page.locator('#telemetrySummary strong').last().textContent()).includes('개입'),'10ms intervention must be visible between model frames');
  await page.evaluate(()=>setTime(.45));assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—');
  assert(await page.locator('[data-graph="speed"] canvas').evaluate(c=>{const x=Math.round(48+.45/2*(c.width-56)),d=c.getContext('2d').getImageData(x,8,1,80).data;for(let i=0;i<d.length;i+=4)if(d[i]===87&&d[i+1]===217&&d[i+2]===176)return false;return true}),'invalid samples must leave a gap');
  await page.evaluate(()=>setTime(.1));
  const canvas=page.locator('[data-graph="speed"] canvas'),box=await canvas.boundingBox();
  await page.mouse.click(box.x+48+.5*(box.width-56),box.y+45);
  assert(Math.abs(await page.evaluate(()=>t)-1)<.02);assert.equal(await page.evaluate(()=>playing),false);
  await page.evaluate(()=>{setTime(.1);toggle()});
  await page.mouse.move(box.x+48+.25*(box.width-56),box.y+45);await page.mouse.down();await page.mouse.move(box.x+48+.4*(box.width-56),box.y+45,{steps:4});await page.mouse.up();
  assert.equal(await page.evaluate(()=>playing),true);assert(Math.abs(await page.evaluate(()=>t)-.8)<.06);await page.evaluate(()=>pause());
  await canvas.focus();await page.keyboard.press('ArrowRight');assert(await page.evaluate(()=>t)>.85);
  await page.locator('#graphZoomIn').click();assert((await page.locator('#graphTime').textContent()).includes('0.3–1.3')||!(await page.locator('#graphTime').textContent()).includes('0.0–2.0'));
  const displayedRange=async()=>(await page.locator('#graphTime').textContent()).split(' · ')[1];
  const centered=async()=>assert(await canvas.evaluate(c=>Math.abs(parseFloat(c.parentElement.querySelector('.telemetry-cursor').style.left)-(48+(c.getBoundingClientRect().width-56)/2))<2),'zoomed playhead should be centered');
  await page.evaluate(()=>setTime(.7));assert.equal(await displayedRange(),'0.2–1.2s');await centered();
  await page.evaluate(()=>toggle());await page.waitForFunction(()=>t>.85);await page.evaluate(()=>pause());await centered();assert.notEqual(await displayedRange(),'0.2–1.2s','range should follow during playback before the playhead reaches an edge');
  for(const play of [false,true]){
   await page.evaluate(play=>{pause();setTime(1);if(play)toggle()},play);
   const zoomBox=await canvas.boundingBox(),x=f=>zoomBox.x+48+f*(zoomBox.width-56),y=zoomBox.y+45;
   await page.mouse.move(x(.3),y);await page.mouse.down();const frozen=await displayedRange();
   await page.mouse.move(x(.7),y,{steps:4});assert.equal(await displayedRange(),frozen,'dragging must freeze the time axis');
   await page.mouse.up();await centered();assert.notEqual(await displayedRange(),frozen,'release should recenter the selected time');assert.equal(await page.evaluate(()=>playing),play);await page.evaluate(()=>pause());
  }
  await page.evaluate(()=>setTime(.1));assert.equal(await displayedRange(),'0.0–1.0s');
  await page.evaluate(()=>setTime(1.9));assert.equal(await displayedRange(),'1.0–2.0s');
  await page.locator('#graphReset').click();assert((await page.locator('#graphTime').textContent()).includes('0.0–2.0'));
  await page.locator('#chooseGraphs').click();assert(await page.locator('#graphDialog').isVisible());assert.equal(await page.locator('#graphOptions input').count(),20);
  for(const input of await page.locator('#graphOptions input').all())await input.check();
  await page.locator('#graphDialog').evaluate(e=>e.scrollTop=0);
  const graphOrder=()=>page.locator('.graph-option input').evaluateAll(es=>es.map(e=>e.value));
  const grab=await page.locator('[data-graph="speed"] .graph-handle').boundingBox(),drop=await page.locator('[data-graph="accelPlan"].graph-option').boundingBox();
  await page.mouse.move(grab.x+grab.width/2,grab.y+grab.height/2);await page.mouse.down();await page.mouse.move(grab.x+grab.width/2,drop.y+drop.height/2,{steps:5});
  const floating=await page.locator('.graph-dragging .graph-handle').boundingBox();assert(Math.abs(floating.y+floating.height/2-(drop.y+drop.height/2))<2,'dragged row should follow the grabbed point');
  assert.equal(await page.locator('.graph-placeholder').count(),1);assert.equal(await page.locator('.graph-dragging').getAttribute('data-graph'),'speed');
  await page.mouse.up();assert.equal(await page.locator('.graph-placeholder').count(),0);assert.equal(await page.locator('.graph-dragging').count(),0);
  assert.deepEqual((await graphOrder()).slice(0,3),['acceleration','accelPlan','speed']);
  assert.equal(await page.locator('.graph-up,.graph-down').count(),0);
  assert(await page.locator('.graph-option').first().evaluate(row=>row.querySelector('.graph-handle').getBoundingClientRect().left>=row.querySelector('label').getBoundingClientRect().right),'handle belongs at the right edge');
  const moveBack=await page.locator('[data-graph="speed"] .graph-handle').boundingBox(),beforePedals=await page.locator('[data-graph="accelPlan"].graph-option').boundingBox();
  await page.mouse.move(moveBack.x+moveBack.width/2,moveBack.y+moveBack.height/2);await page.mouse.down();await page.mouse.move(moveBack.x+moveBack.width/2,beforePedals.y+1,{steps:4});await page.mouse.up();
  assert.deepEqual((await graphOrder()).slice(0,3),['acceleration','speed','accelPlan']);
  assert.equal((await graphOrder())[0],'acceleration');
  const cancelGrab=await page.locator('[data-graph="acceleration"] .graph-handle').boundingBox();
  await page.mouse.move(cancelGrab.x+12,cancelGrab.y+20);await page.mouse.down();await page.mouse.move(cancelGrab.x+12,cancelGrab.y+80);
  await page.keyboard.press('Escape');await page.mouse.up();assert(await page.locator('#graphDialog').isHidden());assert.equal(await page.locator('.graph-placeholder').count(),0);assert.equal(await page.locator('.graph-dragging').count(),0);
  await page.locator('#chooseGraphs').click();assert.equal((await graphOrder())[0],'acceleration');
  await page.locator('#graphOptions input[value="acceleration"]').uncheck();await page.locator('#graphOptions input[value="acceleration"]').check();
  assert.equal(await page.locator('.telemetry-chart').first().getAttribute('data-graph'),'acceleration');
  await page.keyboard.press('Escape');assert(await page.locator('#graphDialog').isHidden());assert(await page.locator('#chooseGraphs').evaluate(e=>e===document.activeElement));assert.equal(await page.locator('.telemetry-chart').count(),20);
  await page.evaluate(()=>setTime(.1));
  for(const [id,value] of [['angle','목표: 3.00'],['autoPedals','가스 출력: 25.00'],['accelPlan','제어 목표: 0.30'],['jerk','요청: 0.40'],['accelRequest','감속 요청: 켜짐'],['longState','속도 제어: 해당'],['longState','비활성: 아님'],['curvature','요청: 0.00123'],['lateralAccel','목표: 1.20'],['rpm','기록값: 1500.00']])assert((await page.locator(`[data-graph="${id}"] .telemetry-legend`).textContent()).includes(value),id+' should show logged data');
  assert((await page.locator('[data-graph="pedals"] .telemetry-source-note').textContent()).includes('기록값이 모두 0'));
  assert((await page.locator('[data-graph="angle"] .telemetry-source-note').textContent()).includes('출력 기록: 이 로그에 유효한 기록 없음'));
  assert(await page.locator('#telemetryGraphs').evaluate(e=>e.scrollHeight>e.clientHeight));
  const videoTop=await page.locator('#video').evaluate(e=>e.getBoundingClientRect().top);
  await page.locator('#telemetryGraphs').evaluate(e=>e.scrollTop=e.scrollHeight);await page.waitForTimeout(100);
  assert.equal(await page.locator('#video').evaluate(e=>e.getBoundingClientRect().top),videoTop,'graph scroll must not move the video');
  await page.locator('#telemetryGraphs').evaluate(e=>e.scrollTop=0);
  if(process.env.RV_SCREENSHOTS)await page.screenshot({path:process.env.RV_SCREENSHOTS+'/telemetry-desktop.png'});
  await page.locator('#roadTab').click();assert(await page.locator('#roadView').isVisible());await page.locator('#telemetryTab').click();assert.equal(reads,1,'switching tabs reuses data');
  await page.reload();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));assert.equal(await page.locator('#telemetryTab').getAttribute('aria-selected'),'true');assert.equal(await page.locator('.telemetry-chart').count(),20);
  assert.equal(await page.locator('.telemetry-chart').first().getAttribute('data-graph'),'acceleration');
  await page.setViewportSize({width:390,height:844});
  await page.locator('#chooseGraphs').click();const dialog=await page.locator('#graphDialog').boundingBox();assert(dialog.x>=0&&dialog.x+dialog.width<=390&&dialog.y>=0&&dialog.y+dialog.height<=844);
  await page.locator('#graphDialog').evaluate(e=>e.scrollTop=0);
  assert(await page.locator('.graph-option').first().evaluate(row=>row.querySelector('.graph-handle').getBoundingClientRect().left>=row.querySelector('label').getBoundingClientRect().right));
  const touchGrab=await page.locator('[data-graph="acceleration"] .graph-handle').boundingBox(),touchDrop=await page.locator('[data-graph="speed"].graph-option').boundingBox();
  const cdp=await page.context().newCDPSession(page),x=touchGrab.x+touchGrab.width/2,y=touchGrab.y+touchGrab.height/2;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:touchDrop.y+touchDrop.height/2}]});
  const touchFloating=await page.locator('.graph-dragging .graph-handle').boundingBox();assert(Math.abs(touchFloating.y+touchFloating.height/2-(touchDrop.y+touchDrop.height/2))<2,'touch dragging should track the finger');
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.deepEqual((await graphOrder()).slice(0,2),['speed','acceleration']);await cdp.detach();
  for(const input of await page.locator('#graphOptions input').all())await input.uncheck();
  await page.locator('#graphDialogClose').click();assert((await page.locator('#telemetryGraphs').textContent()).includes('선택된 그래프가 없습니다'));
  await page.reload();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));assert.equal(await page.locator('.telemetry-chart').count(),0);
  await page.locator('#chooseGraphs').click();await page.locator('#graphOptions input[value="speed"]').check();await page.locator('#graphOptions input[value="intervention"]').check();await page.locator('#graphDialogClose').click();
  if(process.env.RV_SCREENSHOTS)await page.screenshot({path:process.env.RV_SCREENSHOTS+'/telemetry-mobile.png',fullPage:true});
  // Reset a saved custom order without changing the selected graphs; persist across reloads.
  await page.evaluate(()=>localStorage.setItem('roadviewer-graph-order',JSON.stringify(['intervention','speed'])));
  await page.reload();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));
  assert.equal(await page.locator('.telemetry-chart').first().getAttribute('data-graph'),'intervention');
  await page.locator('#chooseGraphs').click();await page.locator('#graphOrderReset').click();
  assert(await page.locator('#graphDialog').isVisible());assert.deepEqual((await graphOrder()).slice(0,5),['speed','acceleration','accelPlan','jerk','rpm']);
  assert.deepEqual(await page.locator('#graphOptions input:checked').evaluateAll(es=>es.map(e=>e.value)),['speed','intervention']);
  assert.deepEqual(await page.locator('.telemetry-chart').evaluateAll(es=>es.map(e=>e.dataset.graph)),['speed','intervention']);
  assert.equal(await page.evaluate(()=>localStorage.getItem('roadviewer-graph-order')),null);
  const resetBox=await page.locator('#graphOrderReset').boundingBox(),closeBox=await page.locator('#graphDialogClose').boundingBox();assert(Math.abs(resetBox.y-closeBox.y)<2&&resetBox.x+resetBox.width<=closeBox.x&&closeBox.x+closeBox.width<=390);
  await page.locator('#graphDialogClose').click();await page.reload();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));
  assert.deepEqual(await page.locator('.telemetry-chart').evaluateAll(es=>es.map(e=>e.dataset.graph)),['speed','intervention']);
  fail=true;await page.reload();await page.waitForSelector('#retryTelemetry');assert((await page.locator('#telemetryStatus').textContent()).includes('재생성'));fail=false;await page.locator('#retryTelemetry').click();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));
  // A stream starting just after the video clock should have a useful initial readout.
  const original=structuredClone(telemetry.streams.carState);
  async function reloadAtStart(){await page.reload();await page.waitForFunction(()=>document.getElementById('graphTime').textContent.includes('s'));assert.equal(await page.evaluate(()=>t),0)}
  for(const offset of [.04,.1]){
   telemetry.streams.carState={...structuredClone(original),times:original.times.map(t=>t+offset)};
   await reloadAtStart();assert.deepEqual(await page.locator('#telemetrySummary strong').allTextContents(),['72.00 km/h','0.00 m/s²','0.00 °','없음']);
   assert((await page.locator('[data-graph="speed"] .telemetry-legend').textContent()).includes('실제: 72.00'));
   await page.evaluate(()=>setTime(.45));assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—','invalid interior data must remain unavailable');
  }
  telemetry.streams.carState.times=original.times.map(t=>t+.101);
  await reloadAtStart();assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'72.00 km/h');assert((await page.locator('#telemetryStatus').textContent()).includes('미리보기'));
  assert.equal(await page.evaluate(()=>{playing=true;render();const value=document.querySelector('#telemetrySummary strong').textContent;pause();return value}),'—','preview must not fill a real gap during playback');
  telemetry.streams.carState.times=original.times.map(t=>t+.04);
  telemetry.streams.carState.values.speed[0]=null;telemetry.streams.carState.values.steeringPressed[0]=null;
  await reloadAtStart();assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),original.values.speed[1].toFixed(2)+' km/h');assert.equal(await page.locator('#telemetrySummary strong').last().textContent(),'없음','preview should find the first valid sample after invalid leading samples');assert((await page.locator('#telemetryStatus').textContent()).includes('0.050'));
  await page.evaluate(()=>setTime(.04));assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—','invalid data at its actual timestamp must stay invalid');assert.equal(await page.locator('#telemetryStatus').textContent(),'');
  telemetry.streams.carState={...structuredClone(original),times:original.times.map(t=>t-.02)};
  for(const values of Object.values(telemetry.streams.carState.values))for(let i=0;i<6;i++)values[i]=null;
  await reloadAtStart();assert.notEqual(await page.locator('#telemetrySummary strong').first().textContent(),'—','invalid samples straddling zero should still preview the first valid sample');assert((await page.locator('#telemetryStatus').textContent()).includes('0.040'));
  telemetry.streams.carState={...structuredClone(original),times:original.times.map(t=>t+.3)};
  await reloadAtStart();assert.deepEqual(await page.locator('#telemetrySummary strong').allTextContents(),['—','—','—','확인 불가'],'a genuinely late stream must remain unavailable');
  telemetry.streams.carState={times:[-.02,0,.02],values:{speed:[72,null,73]}};
  await reloadAtStart();assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—','an interior invalid sample must not borrow future data');
  const tailValues=Object.fromEntries(Object.entries(original.values).map(([key,values])=>[key,values.slice(0,19)]));
  telemetry.streams.carState={times:Array.from({length:19},(_,i)=>i/10),values:structuredClone(tailValues)};
  await reloadAtStart();await page.evaluate(()=>setTime(2));assert.notEqual(await page.locator('#telemetrySummary strong').first().textContent(),'—','short continuous telemetry tail should hold like model/video');assert.equal(await page.locator('#telemetrySummary strong').last().textContent(),'없음');
  telemetry.streams.carState.values.speed[18]=null;telemetry.streams.carState.values.steeringPressed[18]=null;
  await reloadAtStart();await page.evaluate(()=>setTime(2));assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—');assert.equal(await page.locator('#telemetrySummary strong').last().textContent(),'확인 불가','invalid final values must not be held');
  telemetry.streams.carState={times:Array.from({length:19},(_,i)=>i/10-.1),values:structuredClone(tailValues)};
  await reloadAtStart();await page.evaluate(()=>setTime(2));assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—','real short telemetry stays unavailable');
  telemetry.streams.carState={times:[...Array.from({length:16},(_,i)=>i/10),1.8],values:Object.fromEntries(Object.entries(tailValues).map(([key,values])=>[key,values.slice(0,17)]))};
  await reloadAtStart();await page.evaluate(()=>setTime(2));assert.equal(await page.locator('#telemetrySummary strong').first().textContent(),'—','missing tail samples must not be held');
  telemetry.streams.carState={times:[],values:{}};
  await reloadAtStart();assert.deepEqual(await page.locator('#telemetrySummary strong').allTextContents(),['—','—','—','확인 불가'],'missing streams stay unavailable');
  assert.deepEqual(errors,[]);console.log('PASS: telemetry tabs, lazy loading, raw timing, gaps, synchronized seeking/playback, popup choices, persistence, scrolling, mouse/touch reordering, saved order, start-boundary readouts, centered zoom playback/drag and retry');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
